### PR TITLE
Apply customizer feature to all features.

### PR DESCRIPTION
**Pull request by ismailsunni**
Fix when the layer has empty string but still needs to be processed by customizer.feature

### CODE REVIEW

**Comment by gberaudo** [comment]
Hi @ismailsunni , could you please explain your rationale?
If there is no symbolizer, the feature will not be displayed, right?

**Comment by ismailsunni** [comment]
There is a case where the layer has properties that shouldn't be included in the print spec. It might be property that is not serializable to JSON (circular reference) or simply it will make MFP throws an error.

So, even if the feature is not displayed, the "problematic" property is stil lincluded in the json print spec.

See an example: https://github.com/geoadmin/web-mapviewer/blob/master/src/api/print.api.js#L55-L60

**Comment by gberaudo** [comment]
I am still a bit uneasy with your approach.
I think we should:
- not add / send features with no associated style;
- not modify the original feature properties (that will have side effects in applications);
- remove offending properties or non-serializable ones here: https://github.com/geoblocks/mapfishprint/blob/918de2be5e860161b29964530fc26835b1022bf3/src/utils.ts#L122 / https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#the_replacer_parameter
-

**Comment by ismailsunni** [comment]
@gberaudo I agree with your approach. My approach is not solving the issue in the correct location.

So, should we add another parameter to pass a replacer in the `requestReport` function? And then use it we call JSON.stringify?

**Comment by ismailsunni** [comment]
Superseded by #37

**Pull request closed without merging**
